version: "3.8"
services:
  goshop:
    image: "github.com/quangdangfit/goshop"
    build: .
    ports:
      - "8888:8888"
    environment:
      port: 8888
      auth_secret: auth_secret
      database_uri: postgres://default:Q6oNEVtmWxL2@ep-sparkling-bonus-a47f7s5x-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb
      redis_uri: redis:6379
      redis_db: 0

    depends_on:
      - postgres
      - redis

  redis:
    image: "redis:alpine"

  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: splax
      POSTGRES_PASSWORD: Killindem1
      POSTGRES_DB: postgres
      POSTGRES_URL: postgres://splax:Killindem1@postgres:5432/postgres
