environment: production
http_port: 8888
grpc_port: 8889
auth_secret: fsgdhjkggfutydrseawttrheytrdfd6jdhdujtdswejydutyeh5ek5786,9760re9w84ma874a s5 ,44..y//0[{?,y88t}]arsarhae

database_uri: postgres://splax:Killindem1@postgres:5432/postgres

redis_uri: localhost:6379
redis_password:
redis_db: 0
